# Generated by Django 6.0.1 on 2026-04-28 19:20

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0002_verificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True
            ),
        ),
    ]
