# Generated by Django 6.0.1 on 2026-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinebarcode',
            name='barcode_number',
            field=models.CharField(max_length=50),
        ),
    ]
