# Generated by Django 6.0.1 on 2026-05-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_alter_medicinebarcode_barcode_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicinebarcode',
            table='medicine_barcodes',
        ),
    ]
